# Generated by Django 3.2.25 on 2026-06-04 23:06
import django.utils.timezone
from django.db import migrations
from django.db import models

import kolibri.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("task", "Task"),
                        ],
                        max_length=10,
                    ),
                ),
                ("kolibri_version", models.CharField(max_length=100)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "first_occurred",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_occurred",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("first_occurred_run", models.IntegerField(blank=True, null=True)),
                ("first_occurred_uptime", models.FloatField(blank=True, null=True)),
                ("last_occurred_run", models.IntegerField(blank=True, null=True)),
                ("last_occurred_uptime", models.FloatField(blank=True, null=True)),
                ("reported", models.BooleanField(default=False)),
                ("events", models.IntegerField(default=1)),
                ("events_since_reported", models.IntegerField(default=1)),
                ("context", kolibri.core.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServerRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_monotonic", models.FloatField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
