# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-24 00:12
from __future__ import unicode_literals

import django.db.models.deletion
import morango.models.fields.uuids
from django.conf import settings
from django.db import migrations
from django.db import models

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0019_collection_no_mptt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0002_auto_20180221_1115"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualSyncableLesson",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                ("lesson_id", models.UUIDField()),
                ("serialized_lesson", kolibri.core.fields.JSONField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.Collection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.FacilityDataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
