# Generated by Django 3.2.25 on 2026-05-27 03:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_nullable_created_by_assigned_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_created",
                to="kolibriauth.FacilityUser",
            ),
        ),
        migrations.AlterField(
            model_name="lessonassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_lessons",
                to="kolibriauth.FacilityUser",
            ),
        ),
    ]
