name: Build Android App

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tar-url:
        description: 'URL for Kolibri tar file'
        required: true
      signed:
        description: 'Should this be signed with the development key? (mutually exclusive with release)'
        required: false
        type: boolean
        default: false
      release:
        description: 'Is this a release asset?'
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      tar-file-name:
        required: false
        type: string
      tar-url:
        required: false
        type: string
      ref:
        description: 'A ref for this workflow to check out its own repo'
        required: false
        type: string
      signed:
        description: 'Should this be signed with the development key? (mutually exclusive with release)'
        required: false
        type: boolean
        default: false
      release:
        description: 'Is this a release asset?'
        required: false
        type: boolean
        default: false
    secrets:
      # A base64-encoded keystore that contains the key used to sign the app
      # for development builds.
      KOLIBRI_ANDROID_APP_DEVELOPER_KEYSTORE:
        required: false
      # The password for the keystore.
      KOLIBRI_ANDROID_APP_DEVELOPER_KEYSTORE_PASSWORD:
        required: false
      # The password for the key in the keystore.
      KOLIBRI_ANDROID_APP_DEVELOPER_KEYALIAS_PASSWORD:
        required: false
      # A base64-encoded keystore that contains the key used to sign the app
      # for production builds.
      KOLIBRI_ANDROID_APP_PRODUCTION_KEYSTORE:
        required: false
      # The password for the keystore.
      KOLIBRI_ANDROID_APP_PRODUCTION_KEYSTORE_PASSWORD:
        required: false
      # The password for the key in the keystore.
      KOLIBRI_ANDROID_APP_PRODUCTION_KEYALIAS_PASSWORD:
        required: false
      KOLIBRI_ANDROID_PLAY_STORE_API_SERVICE_ACCOUNT_JSON:
        required: false
    outputs:
      apk-file-name:
        description: "APK file name"
        value: ${{ jobs.build_apk.outputs.apk-file-name }}
      version-code:
        description: "Version code"
        value: ${{ jobs.build_apk.outputs.version-code }}

jobs:
  build_apk:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_JSON: '${{ secrets.KOLIBRI_ANDROID_PLAY_STORE_API_SERVICE_ACCOUNT_JSON }}'
    outputs:
      apk-file-name: ${{ steps.get-apk-filename.outputs.apk-file-name }}
      version-code: ${{ steps.get-version-code.outputs.version-code}}
    steps:
    - name: Validate release flag inputs
      if: ${{ (inputs.release == true || github.event.inputs.release == 'true') && (inputs.signed == true || github.event.inputs.signed == 'true') }}
      run: |
        echo "Cannot build a release and signed development APK at the same time."
        exit 1
    - name: Validate tar reference inputs
      if: ${{ !github.event.inputs.tar-file-name && ( (inputs.tar-file-name && inputs.tar-url) || (!inputs.tar-file-name && !inputs.tar-url) ) }}
      run: |
        echo "Must specify only one reference for the tar file to build the APK with."
        exit 1
    - uses: actions/checkout@v6
      if: ${{ !inputs.ref }}
    - uses: actions/checkout@v6
      if: ${{ inputs.ref }}
      with:
        repository: learningequality/kolibri-installer-android
        ref: ${{ inputs.ref }}
    - name: Get SHA of current commit
      id: get-commit
      # Note that we do this, so that we get the same commit regardless
      # of whether this is being run from the local repository with workflow_dispatch
      # or from another repository with workflow_call.
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-python: true
    - name: Download the tarfile from URL for workflow_dispatch
      if: ${{ github.event.inputs.tar-url }}
      env:
        TAR_URL: ${{ github.event.inputs.tar-url }}
      run: make get-tar tar="$TAR_URL"
    - name: Download the tarfile from URL for workflow_call
      if: ${{ inputs.tar-url }}
      env:
        TAR_URL: ${{ inputs.tar-url }}
      run: make get-tar tar="$TAR_URL"
    - name: Download the tarfile from artifacts
      if: ${{ inputs.tar-file-name }}
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.tar-file-name }}
        path: tar
    - name: Install dependencies
      run: uv sync --extra build && uv pip install -r requirements.txt
    - name: Build the aab
      if: ${{ inputs.release == true || github.event.inputs.release == 'true' }}
      env:
        RELEASE_KEYALIAS: LE_RELEASE_KEY
        RELEASE_KEYSTORE_PASSWD: ${{ secrets.KOLIBRI_ANDROID_APP_PRODUCTION_KEYSTORE_PASSWORD }}
        RELEASE_KEYALIAS_PASSWD: ${{ secrets.KOLIBRI_ANDROID_APP_PRODUCTION_KEYALIAS_PASSWORD }}
      run: |
        echo -n "${{ secrets.KOLIBRI_ANDROID_APP_PRODUCTION_KEYSTORE }}" | base64 --decode > production.keystore
        export RELEASE_KEYSTORE=$(realpath production.keystore)
        make kolibri.aab
    - name: Get AAB filename
      if: ${{ inputs.release == true || github.event.inputs.release == 'true' }}
      id: get-aab-filename
      run: echo "aab-file-name=$(ls dist | grep .aab | cat)" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v7
      if: ${{ inputs.release == true || github.event.inputs.release == 'true' }}
      with:
        name: ${{ steps.get-aab-filename.outputs.aab-file-name }}
        path: dist/${{ steps.get-aab-filename.outputs.aab-file-name }}
    - name: Upload the AAB to the Play Store and download the signed Universal APK
      if: ${{ inputs.release == true || github.event.inputs.release == 'true' }}
      env:
        RELEASE_KEYALIAS: LE_RELEASE_KEY
      run: make playstore-upload
    - name: Build the apk
      if: ${{ inputs.signed == true || github.event.inputs.signed == 'true' }}
      env:
        RELEASE_KEYALIAS: LE_DEV_KEY
        RELEASE_KEYSTORE_PASSWD: ${{ secrets.KOLIBRI_ANDROID_APP_DEVELOPER_KEYSTORE_PASSWORD }}
        RELEASE_KEYALIAS_PASSWD: ${{ secrets.KOLIBRI_ANDROID_APP_DEVELOPER_KEYALIAS_PASSWORD }}
      run: |
        echo -n "${{ secrets.KOLIBRI_ANDROID_APP_DEVELOPER_KEYSTORE }}" | base64 --decode > development.keystore
        export RELEASE_KEYSTORE=$(realpath development.keystore)
        make kolibri.apk
    - name: Build the debug apk
      if: ${{ inputs.signed != true && github.event.inputs.signed != 'true' && inputs.release != true && github.event.inputs.release != 'true'}}
      run: make kolibri.apk.unsigned
    - name: Get APK filename
      id: get-apk-filename
      run: echo "apk-file-name=$(ls dist | grep .apk | cat)" >> $GITHUB_OUTPUT
    - name: Get versionCode
      id: get-version-code
      run: echo "version-code=$(cat .version-code)" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.get-apk-filename.outputs.apk-file-name }}
        path: dist/${{ steps.get-apk-filename.outputs.apk-file-name }}
