import os
import zipfile

from build_tools.read_kolibri_version import read_version

VERSION = "0.19.0.dev0+g1234abc"

# What setuptools-scm's version_file_template emits (pyproject.toml).
SCM_VERSION_PY = (
    "# file generated by setuptools-scm\n"
    "# don't change, don't track in version control\n"
    f"__version__ = version = '{VERSION}'\n"
)


def test_reads_version_from_a_tree(tmp_path):
    package_dir = os.path.join(str(tmp_path), "kolibri")
    os.makedirs(package_dir)
    with open(os.path.join(package_dir, "_version.py"), "w") as version_module:
        version_module.write(SCM_VERSION_PY)
    assert read_version(str(tmp_path)) == VERSION


def test_reads_version_from_a_wheel(tmp_path):
    whl = os.path.join(str(tmp_path), "kolibri-0.19.0-py2.py3-none-any.whl")
    with zipfile.ZipFile(whl, "w") as archive:
        archive.writestr("kolibri/_version.py", SCM_VERSION_PY)
    assert read_version(whl) == VERSION
