# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 20:44
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.content.models
import kolibri.core.fields
import kolibri.utils.time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LearnerProgressNotification',
            fields=[
                ('id', kolibri.core.content.models.UUIDField(primary_key=True, serialize=False)),
                (
                    'notification_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Help', 'LessonResourceIndividualNeedsHelpEvent'),
                            ('Lesson', 'LessonIndividualCompletion'),
                            ('Quiz', 'QuizIndividualCompletion'),
                            ('Resource', 'ResourceIndividualCompletion'),
                        ],
                        max_length=200,
                    ),
                ),
                ('user_id', kolibri.core.content.models.UUIDField()),
                ('classroom_id', kolibri.core.content.models.UUIDField()),
                ('contentnode_id', kolibri.core.content.models.UUIDField(null=True)),
                ('lesson_id', kolibri.core.content.models.UUIDField(null=True)),
                ('quiz_id', kolibri.core.content.models.UUIDField(null=True)),
                (
                    'reason',
                    models.CharField(
                        blank=True, choices=[('Multiple', 'MultipleUnsuccessfulAttempts')], max_length=200
                    ),
                ),
                ('timestamp', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time.local_now)),
            ],
        )
    ]
