# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 20:01
from __future__ import unicode_literals

import morango.models
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="NotificationsLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coach_id", morango.models.UUIDField()),
                (
                    "timestamp",
                    kolibri.core.fields.DateTimeTzField(
                        default=kolibri.utils.time_utils.local_now
                    ),
                ),
            ],
        )
    ]
