# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 18:08
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_learnerprogressnotification_quiz_num_correct")
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprogressnotification",
            name="quiz_num_answered",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="learnerprogressnotification",
            name="notification_event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Answered", "Answered"),
                    ("Completed", "Completed"),
                    ("Help", "HelpNeeded"),
                    ("Started", "Started"),
                ],
                max_length=200,
            ),
        ),
    ]
