# Generated by Django 3.2.25 on 2024-07-04 21:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_fix_choices"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="learnerprogressnotification",
            index=models.Index(
                fields=["-timestamp"], name="notificatio_timesta_8ba8b0_idx"
            ),
        ),
    ]
