# Generated by Django 3.2.25 on 2026-04-02 16:58
import morango.models.fields.uuids
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0007_learnerprogressnotification_notificatio_timesta_8ba8b0_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprogressnotification",
            name="course_session_id",
            field=morango.models.fields.uuids.UUIDField(blank=True, null=True),
        ),
    ]
