/*
 * This file defines the API for the core Kolibri app.
 * This file is automatically generated using the kolibri package.json
 * exports and exposes fields by the kolibri-tools package.
 */

const kolibri_apiResource = require('kolibri/apiResource');
const kolibri_apiResources_TaskResource = require('kolibri/apiResources/TaskResource');
const kolibri_client = require('kolibri/client');
const kolibri_components_AuthMessage = require('kolibri/components/AuthMessage');
const kolibri_components_BottomAppBar = require('kolibri/components/BottomAppBar');
const kolibri_components_CoreLogo = require('kolibri/components/CoreLogo');
const kolibri_components_CoreTable = require('kolibri/components/CoreTable');
const kolibri_components_FilterTextbox = require('kolibri/components/FilterTextbox');
const kolibri_components_language_switcher_LanguageSwitcherList = require('kolibri/components/language-switcher/LanguageSwitcherList');
const kolibri_components_language_switcher_LanguageSwitcherModal = require('kolibri/components/language-switcher/LanguageSwitcherModal');
const kolibri_components_pages_AppBarPage = require('kolibri/components/pages/AppBarPage');
const kolibri_components_pages_ImmersivePage = require('kolibri/components/pages/ImmersivePage');
const kolibri_components_pages_NotificationsRoot = require('kolibri/components/pages/NotificationsRoot');
const kolibri_components_SkipNavigationLink = require('kolibri/components/SkipNavigationLink');
const kolibri_components_SyncStatusDisplay = require('kolibri/components/SyncStatusDisplay');
const kolibri_composables_useMinimumKolibriVersion = require('kolibri/composables/useMinimumKolibriVersion');
const kolibri_composables_useNav = require('kolibri/composables/useNav');
const kolibri_composables_useNow = require('kolibri/composables/useNow');
const kolibri_composables_useSnackbar = require('kolibri/composables/useSnackbar');
const kolibri_composables_useTotalProgress = require('kolibri/composables/useTotalProgress');
const kolibri_composables_useUser = require('kolibri/composables/useUser');
const kolibri_constants = require('kolibri/constants');
const kolibri_heartbeat = require('kolibri/heartbeat');
const kolibri_router = require('kolibri/router');
const kolibri_store = require('kolibri/store');
const kolibri_styles_themeConfig = require('kolibri/styles/themeConfig');
const kolibri_uiText_bytesForHumans = require('kolibri/uiText/bytesForHumans');
const kolibri_uiText_commonCoreStrings = require('kolibri/uiText/commonCoreStrings');
const kolibri_uiText_licenses = require('kolibri/uiText/licenses');
const kolibri_urls = require('kolibri/urls');
const kolibri_utils_CatchErrors = require('kolibri/utils/CatchErrors');
const kolibri_utils_appCapabilities = require('kolibri/utils/appCapabilities');
const kolibri_utils_baseClient = require('kolibri/utils/baseClient');
const kolibri_utils_browserInfo = require('kolibri/utils/browserInfo');
const kolibri_utils_i18n = require('kolibri/utils/i18n');
const kolibri_utils_objectSpecs = require('kolibri/utils/objectSpecs');
const kolibri_utils_redirectBrowser = require('kolibri/utils/redirectBrowser');
const kolibri_utils_serverClock = require('kolibri/utils/serverClock');
const kolibri_utils_validators = require('kolibri/utils/validators');
const vue = require('vue');
const vuex = require('vuex');
const _vue_composition_api = require('@vue/composition-api');

export default {
  'kolibri/apiResource': kolibri_apiResource,
  'kolibri/apiResources/TaskResource': kolibri_apiResources_TaskResource,
  'kolibri/client': kolibri_client,
  'kolibri/components/AuthMessage': kolibri_components_AuthMessage,
  'kolibri/components/BottomAppBar': kolibri_components_BottomAppBar,
  'kolibri/components/CoreLogo': kolibri_components_CoreLogo,
  'kolibri/components/CoreTable': kolibri_components_CoreTable,
  'kolibri/components/FilterTextbox': kolibri_components_FilterTextbox,
  'kolibri/components/language-switcher/LanguageSwitcherList':
    kolibri_components_language_switcher_LanguageSwitcherList,
  'kolibri/components/language-switcher/LanguageSwitcherModal':
    kolibri_components_language_switcher_LanguageSwitcherModal,
  'kolibri/components/pages/AppBarPage': kolibri_components_pages_AppBarPage,
  'kolibri/components/pages/ImmersivePage': kolibri_components_pages_ImmersivePage,
  'kolibri/components/pages/NotificationsRoot': kolibri_components_pages_NotificationsRoot,
  'kolibri/components/SkipNavigationLink': kolibri_components_SkipNavigationLink,
  'kolibri/components/SyncStatusDisplay': kolibri_components_SyncStatusDisplay,
  'kolibri/composables/useMinimumKolibriVersion': kolibri_composables_useMinimumKolibriVersion,
  'kolibri/composables/useNav': kolibri_composables_useNav,
  'kolibri/composables/useNow': kolibri_composables_useNow,
  'kolibri/composables/useSnackbar': kolibri_composables_useSnackbar,
  'kolibri/composables/useTotalProgress': kolibri_composables_useTotalProgress,
  'kolibri/composables/useUser': kolibri_composables_useUser,
  'kolibri/constants': kolibri_constants,
  'kolibri/heartbeat': kolibri_heartbeat,
  'kolibri/router': kolibri_router,
  'kolibri/store': kolibri_store,
  'kolibri/styles/themeConfig': kolibri_styles_themeConfig,
  'kolibri/uiText/bytesForHumans': kolibri_uiText_bytesForHumans,
  'kolibri/uiText/commonCoreStrings': kolibri_uiText_commonCoreStrings,
  'kolibri/uiText/licenses': kolibri_uiText_licenses,
  'kolibri/urls': kolibri_urls,
  'kolibri/utils/CatchErrors': kolibri_utils_CatchErrors,
  'kolibri/utils/appCapabilities': kolibri_utils_appCapabilities,
  'kolibri/utils/baseClient': kolibri_utils_baseClient,
  'kolibri/utils/browserInfo': kolibri_utils_browserInfo,
  'kolibri/utils/i18n': kolibri_utils_i18n,
  'kolibri/utils/objectSpecs': kolibri_utils_objectSpecs,
  'kolibri/utils/redirectBrowser': kolibri_utils_redirectBrowser,
  'kolibri/utils/serverClock': kolibri_utils_serverClock,
  'kolibri/utils/validators': kolibri_utils_validators,
  vue: vue,
  vuex: vuex,
  '@vue/composition-api': _vue_composition_api,
};
