from django.db.models import OuterRef
from django.db.models import Q
from django.db.models import Subquery
from django.db.models.aggregates import Count
from django_filters.rest_framework import DjangoFilterBackend
from le_utils.constants import content_kinds
from rest_framework import filters
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.serializers import Serializer
from rest_framework.viewsets import GenericViewSet

from kolibri.core.api import ListModelMixin
from kolibri.core.content import models
from kolibri.core.logger.models import ContentSummaryLog
from kolibri.core.logger.models import MasteryLog

from .filters import OptionalPagination
from .tree import TreeQueryMixin
from .user import UserContentNodeFilter

# Fetched from ContentSummaryLog, not from this viewset's ContentNode queryset,
# so a serializer_class would describe the wrong model.
_PROGRESS_VALUES = (
    "content_id",
    "progress",
    "num_question_answered",
    "num_question_answered_correctly",
    "total_questions",
)


class ContentNodeProgressViewset(TreeQueryMixin, GenericViewSet, ListModelMixin):
    filter_backends = (DjangoFilterBackend, filters.OrderingFilter)
    ordering_fields = ["last_interacted"]
    ordering = ("lft", "id")
    filterset_class = UserContentNodeFilter
    # Use same pagination class as ContentNodeViewset so we can
    # return identically paginated responses.
    # The only deviation is that we only return the results
    # and not the full pagination object, as we expect
    # that the pagination object generated by the ContentNodeViewset
    # will be used to make subsequent page requests.
    pagination_class = OptionalPagination
    # Only here to avoid warnings from DRF YASG schema generation.
    serializer_class = Serializer

    def get_queryset(self):
        user = self.request.user

        queryset = models.ContentNode.objects.filter(available=True)
        if user.is_anonymous:
            user = None

        queryset = queryset.annotate(
            last_interacted=Subquery(
                ContentSummaryLog.objects.filter(
                    content_id=OuterRef("content_id"), user=user
                ).values_list("end_timestamp")[:1]
            )
        )
        return queryset

    def generate_response(self, request, queryset):
        if request.user.is_anonymous:
            return Response([])
        logs = list(
            ContentSummaryLog.objects.filter(
                user=self.request.user,
                content_id__in=queryset.exclude(kind=content_kinds.TOPIC).values_list(
                    "content_id", flat=True
                ),
            )
            .annotate(
                num_question_answered=Subquery(
                    MasteryLog.objects.filter(
                        user=self.request.user,
                        summarylog__content_id=OuterRef("content_id"),
                    )
                    .annotate(
                        num_question_answered=Count("attemptlogs"),
                    )
                    .values("num_question_answered")
                    .order_by("-end_timestamp")[:1]
                ),
                num_question_answered_correctly=Subquery(
                    MasteryLog.objects.filter(
                        user=self.request.user,
                        summarylog__content_id=OuterRef("content_id"),
                    )
                    .annotate(
                        num_question_answered_correctly=Count(
                            "attemptlogs",
                            filter=Q(attemptlogs__correct=1),
                        ),
                    )
                    .values("num_question_answered_correctly")
                    .order_by("-end_timestamp")[:1]
                ),
                total_questions=Subquery(
                    models.ContentNode.objects.filter(
                        content_id=OuterRef("content_id"),
                    ).values("assessmentmetadata__number_of_assessments")[:1]
                ),
            )
            .values(*_PROGRESS_VALUES)
        )
        return Response(logs)

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        page_queryset = self.paginate_queryset(queryset)
        if page_queryset is not None:
            queryset = page_queryset
        return self.generate_response(request, queryset)

    @action(detail=True)
    def tree(self, request, pk=None):
        queryset = self.get_tree_queryset(request, pk)
        return self.generate_response(request, queryset)
