project_identifier_env: CROWDIN_PROJECT
api_key_env: CROWDIN_API_KEY
base_path: ./kolibri/locale
preserve_hierachy: false

files:
  - source: '/en/LC_FRONTEND_MESSAGES/*.json'
    translation: '/%locale_with_underscore%/LC_FRONTEND_MESSAGES/%original_file_name%'
    languages_mapping:
      locale_with_underscore:
        ar: ar
        es: es
        hi: hi

  - source: '/en/LC_MESSAGES/*.po'
    translation: '/%locale_with_underscore%/LC_MESSAGES/%original_file_name%'
      locale_with_underscore:
        ar: ar
        es: es
        hi: hi
