# 400 error based constants
USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
USER_ALREADY_IN_GROUP_IN_CLASS = "USER_ALREADY_IN_GROUP_IN_CLASS"
MISSING_PASSWORD = "MISSING_PASSWORD"
MAX_LENGTH = "MAX_LENGTH"
INVALID = "INVALID"
# 401 error constants
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
# 404 error constants
NOT_FOUND = "NOT_FOUND"
# 403 error constants
PERMISSION_DENIED = "PERMISSION_DENIED"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
