"""
Error constants to be returned from our API endpoints.
Should be replicated in the frontend constants.js for the ERROR_CONSTANTS object.
"""
# 400 error based constants
USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
USER_ALREADY_IN_GROUP_IN_CLASS = "USER_ALREADY_IN_GROUP_IN_CLASS"
MISSING_PASSWORD = "MISSING_PASSWORD"
MAX_LENGTH = "MAX_LENGTH"
INVALID = "INVALID"
UNIQUE = "UNIQUE"
INVALID_NETWORK_LOCATION_FORMAT = "INVALID_NETWORK_LOCATION_FORMAT"
NETWORK_LOCATION_NOT_FOUND = "NETWORK_LOCATION_NOT_FOUND"
# 401 error constants
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
# 404 error constants
NOT_FOUND = "NOT_FOUND"
# 403 error constants
PERMISSION_DENIED = "PERMISSION_DENIED"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
