# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 13:33
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import morango.models.fields.uuids
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content_id", models.CharField(max_length=50)),
                ("contentnode_id", models.CharField(max_length=50)),
                ("channel_id", models.CharField(max_length=50)),
                (
                    "facility_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together=set(
                [("facility_user", "content_id", "contentnode_id", "channel_id")]
            ),
        ),
    ]
