project_identifier: kolibri
api_key_env: CROWDIN_API_KEY

base_path: '../kolibri/locale'

preserve_hierachy: false

files:
  - source: '/en/LC_FRONTEND_MESSAGES/*.json'
    translation: '/%locale_with_underscore%/LC_FRONTEND_MESSAGES/%original_file_name%'
    languages_mapping:
      locale_with_underscore:
        ar: ar
        fa: fa
        kn: kn
        mr: mr
        my: my
        ny: nyn
        ta: ta
        te: te
        yo: yo
        zu: zu

  - source: '/en/LC_MESSAGES/*.po'
    translation: '/%locale_with_underscore%/LC_MESSAGES/%original_file_name%'
    languages_mapping:
      locale_with_underscore:
        ar: ar
        fa: fa
        kn: kn
        mr: mr
        my: my
        ny: nyn
        ta: ta
        te: te
        yo: yo
        zu: zu
