# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 21:20
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('instance_id', models.CharField(blank=True, max_length=32)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
