# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 16:39
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="last_available",
            field=models.DateTimeField(default=datetime.datetime(1000, 4, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name="networklocation",
            name="last_unavailable",
            field=models.DateTimeField(default=datetime.datetime(1000, 4, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name="networklocation",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
