# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 00:44
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networklocation',
            old_name='nickname',
            new_name='device_name',
        ),
        migrations.AddField(
            model_name='networklocation',
            name='application',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='networklocation',
            name='kolibri_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networklocation',
            name='operating_system',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
