# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-27 15:02
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0002_general_network_location_data_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="subset_of_users_device",
            field=models.BooleanField(default=False),
        ),
    ]
