# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-15 20:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0005_add_connection_tracking_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="min_content_schema_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
