# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-28 16:47
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.discovery.models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0007_auto_20230322_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinneddevice",
            name="id",
            field=models.CharField(
                default=kolibri.core.discovery.models._uuid_string,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
