# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-08 17:48
from __future__ import unicode_literals

import sys

from django.db import migrations


def _is_test():
    """
    Check if we are running in a test environment, this migration doesn't work in a test environment
    but works otherwise.
    """
    from django.conf import settings

    return settings.TESTING


def set_location_type(apps, schema_editor):
    if _is_test():
        return
    NetworkLocation = apps.get_model("discovery", "NetworkLocation")
    NetworkLocation.objects.filter(dynamic=True).update(location_type="dynamic")
    NetworkLocation.objects.filter(dynamic=False).update(location_type="static")


def revert_location_type(apps, schema_editor):
    if _is_test():
        return
    NetworkLocation = apps.get_model("discovery", "NetworkLocation")
    NetworkLocation.objects.filter(location_type="dynamic").update(dynamic=True)
    NetworkLocation.objects.filter(location_type="static").update(dynamic=False)


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0009_add_location_type"),
    ]

    operations = [
        migrations.RunPython(
            set_location_type,
            reverse_code=revert_location_type,
            # make sure NetworkLocationRouter routes this migration to the correct database
            hints={"model_name": "networklocation"},
        )
    ]
