# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-17 23:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0011_remove_networklocation_dynamic"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pinneddevice",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="pinneddevice",
            name="user",
        ),
        migrations.DeleteModel(
            name="PinnedDevice",
        ),
    ]
