# Generated by Django 3.2.25 on 2026-07-02 21:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0013_recreate_pinned_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalHostname",
            fields=[
                (
                    "hostname",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ["hostname"],
            },
        ),
    ]
