# Generated by Django 3.2.25 on 2026-05-21 20:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0013_recreate_pinned_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="is_provisioned",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
