# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 23:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kolibri.content.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolibriauth', '0002_auto_20160318_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentInteractionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('channel_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('start_timestamp', models.DateTimeField()),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('item_session', kolibri.content.models.UUIDField(default=uuid.uuid4, editable=False, max_length=32)),
                ('kind', models.CharField(blank=True, max_length=200)),
                ('extra_fields', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRatingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('channel_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ease', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSummaryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('last_channel_id', kolibri.content.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, max_length=32)),
                ('start_timestamp', models.DateTimeField()),
                ('last_activity_timestamp', models.DateTimeField(blank=True, null=True)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('kind', models.CharField(blank=True, max_length=200)),
                ('extra_fields', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.TextField(blank=True)),
                ('start_timestamp', models.DateTimeField()),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pages', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser')),
            ],
        ),
    ]
