# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsummarylog',
            name='duration',
        ),
        migrations.AddField(
            model_name='contentsessionlog',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='start_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='time_spent',
            field=models.FloatField(default=0.0, help_text='(in seconds)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='start_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='time_spent',
            field=models.FloatField(default=0.0, help_text='(in seconds)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
