# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentinteractionlog',
            name='item_session',
        ),
    ]
