# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20161024_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionlog',
            name='completion_timestamp',
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='last_interaction_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
