# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:18
from __future__ import unicode_literals

from django.db import migrations
import kolibri.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_remove_contentsummarylog_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsummarylog',
            name='channel_id',
            field=kolibri.content.models.UUIDField(db_index=True, null=True),
        ),
    ]
