# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 14:02
from __future__ import unicode_literals

import kolibri.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20170309_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattemptlog',
            name='channel_id',
            field=kolibri.content.models.UUIDField(default='78eed5c0b59b30c0a40c94c17c849af6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examattemptlog',
            name='content_id',
            field=kolibri.content.models.UUIDField(default='78eed5c0b59b30c0a40c94c17c849af6'),
            preserve_default=False,
        ),
    ]
