# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-13 17:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0003_auto_20170309_1853'),
        ('logger', '0005_auto_20170330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptlog',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examattemptlog',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser'),
            preserve_default=False,
        ),
    ]
