# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20170413_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='completion_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
