# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-30 14:18
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_examlog_completion_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptlog',
            name='answer',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='attemptlog',
            name='interaction_history',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='extra_fields',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='extra_fields',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='answer',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='interaction_history',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='mastery_criterion',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
