# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 22:25
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_auto_20170430_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptlog',
            name='answer',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='answer',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
