# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 22:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0003_auto_20170309_1853'),
        ('logger', '0009_auto_20170502_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentratinglog',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='contentratinglog',
            name='user',
        ),
        migrations.AddField(
            model_name='masterylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityUser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContentRatingLog',
        ),
    ]
