# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 20:01
from __future__ import unicode_literals

import morango.utils.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20170509_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attemptlog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='attemptlog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='contentsessionlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentsessionlog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contentsessionlog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='contentsummarylog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentsummarylog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contentsummarylog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='examattemptlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examattemptlog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='examattemptlog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='examlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examlog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='examlog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='masterylog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterylog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='masterylog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='attemptlog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
    ]
