# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 04:00
from __future__ import unicode_literals

import morango.utils.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20170510_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='attemptlog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='attemptlog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='attemptlog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='contentsessionlog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='contentsummarylog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='examattemptlog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='masterylog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
