# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('kolibriauth', '0001_initial'), ('kolibriauth', '0002_baseuser__is_device_owner')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceOwner',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kolibriauth.baseuser',),
        ),
        migrations.CreateModel(
            name='FacilityUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kolibriauth.baseuser',),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='_is_device_owner',
            field=models.BooleanField(default=None, editable=False),
        ),
    ]
