# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='_is_device_owner',
            field=models.BooleanField(default=None, editable=False),
        ),
    ]
