# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 18:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0002_auto_20170208_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[(b'facility', 'Facility'), (b'classroom', 'Classroom'), (b'learnergroup', 'Learner group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceowner',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters and digits only', max_length=30, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters and numbers.')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='facilityuser',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters and digits only', max_length=30, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters and numbers.')], verbose_name='username'),
        ),
    ]
