# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0002_auto_20160203_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kolibriauth.collection',),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kolibriauth.collection',),
        ),
        migrations.CreateModel(
            name='LearnerGroup',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kolibriauth.collection',),
        ),
    ]
