# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0002_auto_20160318_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceowner',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='kolibriauth.FacilityUser'),
        ),
    ]
