# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


def combine_names(apps, schema_editor):
    # We can't import the FacilityUser model and DeviceOwner model directly
    # as they may be a newer version than this migration expects.
    # We use the historical version.
    FacilityUser = apps.get_model("kolibriauth", "FacilityUser")
    for user in FacilityUser.objects.all():
        user.full_name = "%s %s" % (user.first_name, user.last_name)
        user.save()

    DeviceOwner = apps.get_model("kolibriauth", "DeviceOwner")
    for owner in DeviceOwner.objects.all():
        owner.full_name = "%s %s" % (owner.first_name, owner.last_name)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0003_auto_20160808_1838'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
