# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 04:00
from __future__ import unicode_literals

import morango.utils.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0004_auto_20170510_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='collection',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='learner_can_delete_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='learner_can_edit_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='learner_can_edit_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='learner_can_edit_username',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilitydataset',
            name='learner_can_sign_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilityuser',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='facilityuser',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='facilityuser',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='facilityuser',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='membership',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='_morango_partition',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='role',
            name='_morango_source_id',
            field=models.CharField(editable=False, max_length=96),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
