# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0004_auto_20160808_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deviceowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facilityuser',
            name='last_name',
        ),
    ]
