# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0006_auto_20171206_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydataset',
            name='preset',
            field=models.CharField(choices=[('informal', 'Informal and personal use'), ('nonformal', 'Self-managed'), ('formal', 'Admin-managed')], default='nonformal', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='facilityuser',
            unique_together=set([]),
        ),
    ]
