steps:
  - label: Build Python packages
    command:
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - trigger: "kolibri-macos"
    label: ":mac:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      branch: "v0.2.1"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - label: ":android:"
    trigger: "kolibri-android-installer"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - trigger: "kolibri-debian"
    label: ":debian:"
    key: deb-build
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - trigger: "kolibri-windows"
    label: ":windows:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - trigger: "kolibri-raspbian-image"
    label: ":raspberry-pi:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"
    depends_on:
      - deb-build

  - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh
    if: build.tag != null
