steps:
  - label: Build Python packages
    command:
     - make docker-clean
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - label: Build Windows installer
    command: .buildkite/build_windows_installer.sh

  - label: Build Debian Packages
    command: .buildkite/build_debian_pkgs.sh

  - wait

  - label: Upload artifacts
    command: .buildkite/setup_and_upload_artifact.sh

  - wait

  - label: Cleaning up
    command: make docker-clean

  - block: "Sign Windows installer?"
  - label: Sign Windows installer
    command: .buildkite/sign_windows_installer.bat
    agents:
      queue: "windows-sign"

  - wait

  - label: Upload new artifacts
    command: .buildkite/setup_and_upload_artifact.sh

  - block: "Create APK?"
  - label: Build the Android APK file
    command:
     - mkdir -p dist
     - .buildkite/build_apk.sh

  - block: "Test .debs?"
  - label: Test on Trusty, Xenial, Bionic
    command:
     - mkdir -p dist
     - buildkite-agent artifact download 'dist/*.deb' dist/
     - make docker-deb-test
