steps:
  - label: Build Python packages
    command:
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - trigger: "kolibri-debian"
    label: ":debian:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - trigger: "kolibri-windows"
    label: ":windows:"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        LE_TRIGGERED_FROM_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        LE_TRIGGERED_FROM_JOB_ID: "${BUILDKITE_JOB_ID}"
        # Determines whether build will be autoblocked or not.
        # Autoblock unless there's a tag associated with the commit. Usually a release.
        LE_KOLIBRI_RELEASE: "${BUILDKITE_TAG:-false}"

  - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh
    agents:
        vader=true
    if: build.tag != null

  - block: "Create integration testing worksheet?"
  - label: Create integration testing
    command: .buildkite/build_worksheet.sh
