steps:
  - label: Build Python packages
    command:
     - make docker-clean
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - label: Build Debian Packages
    command: .buildkite/build_debian_pkgs.sh
    key: deb-build

  - wait

  # NOTE: Uploading artifacts should only happen once. Doing so twice during the
  # release process causes an error, which blocks the execution of the steps.
  - label: Upload artifacts
    command: .buildkite/setup_and_upload_artifact.sh


  - label: Cleaning up
    command: make docker-clean

  - block: "Test .debs?"
  - label: Test on Trusty, Xenial, Bionic
    command:
     - mkdir -p dist
     - buildkite-agent artifact download 'dist/*.deb' dist/
     - make docker-deb-test
