steps:
  - label: Build Python packages
    command: mkdir -p dist && .buildkite/build_whl.sh

  - wait

  - label: Build Windows installer
    command: .buildkite/build_windows_installer.sh

  - wait

  - label: Build Debian Packages
    command: .buildkite/build_debian_pkgs.sh

  - wait

  - label: Upload artifacts
    command: .buildkite/setup_and_upload_artifact.sh

  - label: Sign Windows installer
    command: .buildkite/sign_windows_installer.bat
    agents:
      queue: "windows-sign"

  - wait

  - label: Cleaning up
    command: make dockerenv-clean

  - block: "Create release artifacts?"

  - label: Build the Android APK file
    command: mkdir -p dist && .buildkite/build_apk.sh
