# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("kolibriauth", "0004_auto_20170816_1607")]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="preset",
            field=models.CharField(
                choices=[
                    ("formal", "Admin-managed"),
                    ("informal", "Informal and personal use"),
                    ("nonformal", "Self-managed"),
                ],
                default="formal",
                max_length=50,
            ),
        )
    ]
