# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 23:56
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("kolibriauth", "0010_auto_20180320_1320")]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="show_download_button_in_learn",
            field=models.BooleanField(default=True),
        )
    ]
