# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 17:48
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0011_facilitydataset_show_download_button_in_learn")
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="allow_guest_access",
            field=models.BooleanField(default=True),
        )
    ]
