# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 16:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("kolibriauth", "0012_facilitydataset_allow_guest_access")]

    operations = [
        migrations.AlterField(
            model_name="facilityuser",
            name="username",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Letters and digits only",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "[\\s`~!@#$%^&*()\\-+={}\\[\\]\\|\\\\\\/:;\"\\'<>,\\.\\?]",
                        "Enter a valid username. This value can contain only letters, numbers, and underscores.",
                        inverse_match=True,
                    )
                ],
                verbose_name="username",
            ),
        )
    ]
