# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.core.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0013_auto_20180917_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityuser',
            name='birth_year',
            field=models.CharField(blank=True, default='', max_length=10, validators=[kolibri.core.auth.models.validate_birth_year]),
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('DECLINE', 'Prefers not to say'), ('DEFER', 'Defers for later')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='facilityuser',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
