# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 14:13
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0013_auto_20180917_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='subscriptions',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
    ]
