# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0014_auto_20190815_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualLearnersGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('kolibriauth.collection',),
        ),
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('facility', 'Facility'), ('classroom', 'Classroom'), ('learnergroup', 'Learner group'), ('individuallearnersgroup', 'Individual learners group')], max_length=23),
        ),
    ]
