# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kolibriauth", "0015_facilitydataset_registered")]

    operations = [
        migrations.CreateModel(
            name="AdHocGroup",
            fields=[],
            options={"indexes": [], "proxy": True},
            bases=("kolibriauth.collection",),
        ),
        migrations.AlterField(
            model_name="collection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("facility", "Facility"),
                    ("classroom", "Classroom"),
                    ("learnergroup", "Learner group"),
                    ("adhoclearnersgroup", "Individual learners group"),
                ],
                max_length=20,
            ),
        ),
    ]
