# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0016_add_adhoclearnersgroup_collection_kind"),
        ("device", "0005_auto_20191203_0951"),
    ]

    operations = [
        migrations.RemoveField(model_name="facilitydataset", name="allow_guest_access")
    ]
