# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-17 17:51
from django.db import migrations
from django.db import models

import kolibri.core.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0023_change_extra_fields_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityuser",
            name="username",
            field=models.CharField(
                help_text="Required. 254 characters or fewer.",
                max_length=254,
                validators=[kolibri.core.auth.models.validate_username],
                verbose_name="username",
            ),
        ),
    ]
