# Generated by Django 3.2.25 on 2025-05-21 19:19
from django.db import migrations

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0027_alter_facilitydataset_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityuser",
            name="date_deleted",
            field=kolibri.core.fields.DateTimeTzField(blank=True, null=True),
        ),
    ]
