# Generated by Django 3.2.25 on 2025-05-30 16:29
from django.db import migrations

import kolibri.core.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0028_facilityuser_date_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="facilityuser",
            managers=[
                ("objects", kolibri.core.auth.models.FacilityUserModelManager()),
                (
                    "soft_deleted_objects",
                    kolibri.core.auth.models.SoftDeletedFacilityUserModelManager(),
                ),
            ],
        ),
    ]
