# Generated by Django 3.2.25 on 2025-06-28 16:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0030_alter_facilityuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityuser",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
