# Generated by Django 3.2.25 on 2026-03-18 19:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0032_alter_facilityuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="enable_mark_attendance",
            field=models.BooleanField(default=False),
        ),
    ]
