# Generated by Django 3.2.25 on 2026-03-11 18:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0032_alter_facilityuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityuser",
            name="picture_password",
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="facilityuser",
            unique_together={("dataset", "picture_password")},
        ),
    ]
