# Generated by Django 3.2.25 on 2026-03-20 18:18
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0033_facilitydataset_enable_mark_attendance"),
        ("kolibriauth", "0033_facilityuser_add_picture_password"),
    ]

    operations = []
