# Generated by Django 3.2.25 on 2026-03-23 19:24
from django.db import migrations

import kolibri.core.fields
import kolibri.core.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0034_merge_attendance_setting_picture_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="picture_password_settings",
            field=kolibri.core.fields.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "properties": {
                                "icon_style": {
                                    "enum": ["standard", "colorful"],
                                    "type": "string",
                                },
                                "show_icon_text": {"type": "boolean"},
                            },
                            "required": ["icon_style", "show_icon_text"],
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
