# Generated by Django 3.2.25 on 2026-06-28 01:25

from django.db import migrations, models


def enable_qr_login_for_existing_facilities(apps, schema_editor):
    FacilityDataset = apps.get_model("kolibriauth", "FacilityDataset")
    FacilityDataset.objects.filter(enable_qr_login=False).update(enable_qr_login=True)


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0037_facilityuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydataset',
            name='enable_qr_login',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            enable_qr_login_for_existing_facilities,
            migrations.RunPython.noop,
        ),
    ]
