# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmetadatacache',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
