# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 16:43
from __future__ import unicode_literals

from django.db import migrations
import kolibri.content.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160630_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='id',
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='instance_id',
            field=kolibri.content.models.UUIDField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
