# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160802_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='stemmed_metaphone',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
