# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170825_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='license',
        ),
        migrations.AddField(
            model_name='contentnode',
            name='license_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='license_name',
            field=models.CharField(default='All Rights Reserved', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
