# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20161222_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_subcode',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
