# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 22:42
from __future__ import unicode_literals

import django.db.models.deletion
import kolibri.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0003_auto_20170309_1853'),
        ('content', '0006_auto_20170309_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMetaData',
            fields=[
                ('id', kolibri.content.models.UUIDField(primary_key=True, serialize=False)),
                ('assessment_item_ids', models.TextField()),
                ('number_of_assessments', models.IntegerField()),
                ('mastery_model', models.CharField(max_length=200)),
                ('randomize', models.BooleanField(default=False)),
                ('is_manipulable', models.BooleanField(default=False)),
                ('contentnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessmentmetadata', to='content.ContentNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', kolibri.content.models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('question_count', models.IntegerField()),
                ('question_sources', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='kolibriauth.Collection')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='kolibriauth.FacilityUser')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='kolibriauth.FacilityUser')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='kolibriauth.Collection')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='content.Exam')),
            ],
        ),
    ]
