# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_assessmentmetadata_exam_examassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmetadata',
            name='contentnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentmetadata', to='content.ContentNode'),
        ),
    ]
