# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-30 13:37
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170406_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmetadata',
            name='assessment_item_ids',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='assessmentmetadata',
            name='mastery_model',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_sources',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
