# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 20:01
from __future__ import unicode_literals

import morango.utils.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170430_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='exam',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='_morango_dirty_bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='_morango_partition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='_morango_source_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='id',
            field=morango.utils.uuids.UUIDField(primary_key=True, serialize=False),
        ),
    ]
