# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170430_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='license_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
