# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 22:29
from __future__ import unicode_literals

import kolibri.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170430_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='content_id',
            field=kolibri.content.models.UUIDField(db_index=True),
        ),
    ]
