# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 02:50
from __future__ import unicode_literals

import kolibri.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_license_license_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='content_id',
            field=kolibri.content.models.UUIDField(db_index=True),
        ),
    ]
