# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20170511_0400'),
        ('content', '0012_license_license_description'),
    ]

    operations = [
    ]
