export const DateRangeFilters = {
  LAST_7_DAYS: 'LAST_7_DAYS',
  LAST_30_DAYS: 'LAST_30_DAYS',
  LAST_365_DAYS: 'LAST_365_DAYS',
  ALL_TIME: 'ALL_TIME',
  CUSTOM: 'CUSTOM',
  CUSTOM_APPLIED: 'CUSTOM_APPLIED',
};
