# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-24 03:19
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("logger", "0006_remove_examattemptlog_channel_id")]

    operations = [
        migrations.AddField(
            model_name="contentsessionlog",
            name="visitor_id",
            field=models.UUIDField(blank=True, null=True),
        )
    ]
