# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logger", "0006_remove_examattemptlog_channel_id")]

    operations = [
        migrations.AddField(
            model_name="contentsessionlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        )
    ]
