# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 07:28
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0007_contentsessionlog_visitor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersessionlog",
            name="device_info",
            field=models.CharField(null=True, blank=True, max_length=100),
        ),
    ]
