# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-15 00:33
from __future__ import unicode_literals

import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0008_usersessionlog_device_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsessionlog",
            name="channel_id",
            field=morango.models.fields.uuids.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentsummarylog",
            name="channel_id",
            field=morango.models.fields.uuids.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="masterylog",
            name="mastery_level",
            field=models.IntegerField(),
        ),
    ]
