# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-18 00:38
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0010_min_length_validation"),
    ]

    operations = [
        # We do the migration in two stages so that data recorded in older versions
        # have the new field just set to null, but new records will have it set to 0 by default.
        # This should also make sure that migrations on larger databases are quicker too.
        migrations.AddField(
            model_name="masterylog",
            name="time_spent",
            field=models.FloatField(blank=True, help_text="(in seconds)", null=True),
        ),
        migrations.AlterField(
            model_name="masterylog",
            name="time_spent",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="(in seconds)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
