# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-09 18:01
import django.db.models.deletion
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0020_facilitydataset_extra_fields"),
        ("logger", "0011_masterylog_time_spent"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerateCSVLogRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_start_date", kolibri.core.fields.DateTimeTzField()),
                ("selected_end_date", kolibri.core.fields.DateTimeTzField()),
                (
                    "date_requested",
                    kolibri.core.fields.DateTimeTzField(
                        default=kolibri.utils.time_utils.local_now
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[("session", "Session"), ("summary", "Summary")],
                        max_length=7,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.Facility",
                    ),
                ),
            ],
        ),
    ]
