# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-16 19:08
from django.db import migrations

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0012_generatecsvlogrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatecsvlogrequest",
            name="selected_end_date",
            field=kolibri.core.fields.DateTimeTzField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generatecsvlogrequest",
            name="selected_start_date",
            field=kolibri.core.fields.DateTimeTzField(blank=True, null=True),
        ),
    ]
