"""
Tooling for generating i18n strings using Kolibri's translation machinery.
"""

import json
import os
import sys
import xml.etree.ElementTree as ET
from importlib import resources

# Add extracted Kolibri tar to Python path
EXTRACTED_TAR_PATH = os.path.join(os.path.dirname(__file__), "../tar/extracted")
if os.path.exists(EXTRACTED_TAR_PATH):
    sys.path.insert(0, EXTRACTED_TAR_PATH)


# By default we will map the locale code to e.g. "en-us" to "en-rUS"
# except for mapping specified below.

locale_code_map = {
    "es-419": "b+es+419",
    "zh-hans": "zh",
}

# The language code that will be used for the non-prefixed values folder
DEFAULT_LANGUAGE = "en"


def _find_string(lang, string):
    from django.utils.translation import gettext as _
    from django.utils.translation import override
    from django.utils.translation import to_locale

    from kolibri.main import initialize

    initialize(skip_update=True)

    with override(lang):
        new_string = _(string)
        if new_string != string and new_string:
            return new_string

    for message_file in os.listdir(
        resources.files("kolibri") / "locale" / "en" / "LC_MESSAGES"
    ):
        if message_file.endswith(".json"):
            with open(
                resources.files("kolibri")
                / "locale"
                / "en"
                / "LC_MESSAGES"
                / message_file,
                "r",
            ) as f:
                messages = json.load(f)
                for key, value in messages.items():
                    if value == string:
                        try:
                            # Do this in case we have a legacy translation file - this should be cleaned up
                            # in a future version of Kolibri
                            with open(
                                resources.files("kolibri")
                                / "locale"
                                / to_locale(lang)
                                / "LC_MESSAGES"
                                / message_file,
                                "r",
                            ) as lang_message_file:
                                messages = json.load(lang_message_file)
                                new_string = messages[key]
                                if new_string != string and new_string:
                                    return new_string
                                # If we have a translation but the string is no different in translation, it means we should
                                # not include it in the strings.xml file
                                return None
                        except FileNotFoundError:
                            break
    return None


# Strings that we only access from Python, so we don't need to include them in the strings.xml file
PYTHON_ONLY_STRINGS = []


def create_resource_files():
    """
    Read each language directory and create resource files in the corresponding Android values folder.
    """
    en_strings_file = os.path.join(
        os.path.dirname(__file__),
        "../app/src/main/res/values/strings.xml",
    )

    en_strings_tree = ET.parse(en_strings_file)

    en_strings_root = en_strings_tree.getroot()

    from kolibri.utils.i18n import KOLIBRI_SUPPORTED_LANGUAGES

    all_langs = sorted(KOLIBRI_SUPPORTED_LANGUAGES)

    for lang_dir in all_langs:
        if lang_dir == DEFAULT_LANGUAGE:
            continue

        if lang_dir in locale_code_map:
            locale_dir = locale_code_map[lang_dir]
        else:
            parts = lang_dir.split("-")
            if len(parts) == 1:
                locale_dir = lang_dir
            elif len(parts) == 2:
                locale_dir = f"{parts[0]}-r{parts[1].upper()}"
            else:
                raise ValueError(f"Invalid language code: {lang_dir}")
        dir_name = f"values-{locale_dir}"

        values_dir = os.path.join(
            os.path.dirname(__file__),
            "../app/src/main/res",
            dir_name,
        )

        os.makedirs(values_dir, exist_ok=True)

        new_root = ET.Element("resources")
        new_tree = ET.ElementTree(element=new_root)

        for string in en_strings_root.findall("string"):
            name = string.get("name")
            value = _find_string(lang_dir, string.text)
            if value is None:
                continue
            new_string = ET.SubElement(
                new_root, "string", attrib={"name": name}
            )
            new_string.text = value

        new_tree.write(
            os.path.join(values_dir, "strings.xml"),
            encoding="utf-8",
            xml_declaration=True,
        )

    # Create the Python strings file (only if there are Python-only strings)
    if PYTHON_ONLY_STRINGS:
        output = "# This file is auto-generated by the create_strings.py script. Do not edit it directly."
        output += "\ni18n_strings = {"
        for python_string in PYTHON_ONLY_STRINGS:
            output += "\n    " + f"'{python_string}': " + "{"
            for lang_dir in all_langs:
                value = _find_string(lang_dir, python_string)
                if value is None:
                    continue
                output += f"\n        '{lang_dir}': '{value}', "
            output += "\n    },"
        output += "\n}\n"
        with open(
            os.path.join(
                os.path.dirname(__file__), "../app/src/main/python/strings.py"
            ),
            "w",
        ) as f:
            f.write(output)


def main():
    """
    Run the script to generate the Android resource files with translated strings.
    """
    create_resource_files()


if __name__ == "__main__":
    # Actually run the script
    main()
