<template>

  <div
    ref="mainWrapper"
    class="main-wrapper"
    :style="mainWrapperStyles"
  >
    <div
      v-if="!loading"
      :class="fullScreen ? 'scrolling-pane' : 'content'"
      :style="contentStyles"
    >
      <KPageContainer v-if="notAuthorized">
        <AuthMessage
          :authorizedRole="authorizedRole"
          :header="authorizationErrorHeader"
          :details="authorizationErrorDetails"
          :style="mainStyles"
        />
      </KPageContainer>
      <KPageContainer v-else-if="error">
        <AppError />
      </KPageContainer>

      <div
        v-else
        id="main"
        role="main"
        tabindex="-1"
        class="main"
        :style="mainStyles"
      >
        <slot></slot>
      </div>
    </div>

    <GlobalSnackbar />
    <UpdateNotification
      v-if="!loading && showNotification"
      :id="mostRecentNotification.id"
      :title="mostRecentNotification.title"
      :msg="mostRecentNotification.msg"
      :linkText="mostRecentNotification.linkText"
      :linkUrl="mostRecentNotification.linkUrl"
      @submit="dismissUpdateModal"
    />
  </div>

</template>


<script>

  import { mapState } from 'vuex';
  import Lockr from 'lockr';
  import { UPDATE_MODAL_DISMISSED } from 'kolibri.coreVue.vuex.constants';
  import { currentLanguage, defaultLanguage } from 'kolibri.utils.i18n';
  import AuthMessage from 'kolibri.coreVue.components.AuthMessage';
  import GlobalSnackbar from './GlobalSnackbar.vue';
  import UpdateNotification from './UpdateNotification.vue';
  import AppError from './AppError';

  export default {
    name: 'NotificationsRoot',
    components: {
      AppError,
      AuthMessage,
      GlobalSnackbar,
      UpdateNotification,
    },
    props: {
      // AUTHORIZATION SPECIFIC
      authorized: {
        type: Boolean,
        required: false,
        default: true,
      },
      authorizedRole: {
        type: String,
        default: null,
      },
      authorizationErrorHeader: {
        type: String,
        default: null,
      },
      authorizationErrorDetails: {
        type: String,
        default: null,
      },
      // Prop that determines whether to show nav components and provide margins
      fullScreen: {
        type: Boolean,
        default: false,
      },
      // Prop that determines if the page contains an embedded sidebar
      hasSidebar: {
        type: Boolean,
        default: false,
      },
      maxMainWidth: {
        type: Number,
        required: false,
        default: 1000,
      },
      // reserve space at the bottom for floating widgets
      marginBottom: {
        type: Number,
        default: 0,
      },
    },
    data() {
      return {
        notificationModalShown: true,
      };
    },
    computed: {
      ...mapState({
        error: state => state.core.error,
        loading: state => state.core.loading,
        notifications: state => state.core.notifications,
      }),
      mainWrapperStyles() {
        if (this.$isPrint) {
          return {};
        }

        return {
          backgroundColor: this.$themePalette.grey.v_100,
          paddingBottom: `${this.marginBottom}px`,
        };
      },
      notAuthorized() {
        // catch "not authorized" error, display AuthMessage
        if (
          this.error &&
          this.error.response &&
          this.error.response.status &&
          this.error.response.status == 403
        ) {
          return true;
        }
        return !this.authorized;
      },
      showNotification() {
        if (
          (this.isAdmin || this.isSuperuser) &&
          !Lockr.get(UPDATE_MODAL_DISMISSED) &&
          this.notificationModalShown &&
          this.notifications.length !== 0
        ) {
          return true;
        }
        return false;
      },
      mostRecentNotification() {
        let languageCode = defaultLanguage.id;
        // notifications should already be ordered by timestamp
        const notification = this.notifications[0];
        // check if translated message is available for current language
        if (notification.i18n[currentLanguage] !== undefined) {
          languageCode = currentLanguage;
        }
        // i18n data structure generated by nutritionfacts_i18n.py
        return {
          id: notification.id,
          title: notification.i18n[languageCode].title,
          msg: notification.i18n[languageCode].msg,
          linkText: notification.i18n[languageCode].link_text,
          linkUrl: notification.link_url,
        };
      },
      contentStyles() {
        if (this.fullScreen || this.$isPrint || this.hasSidebar) {
          return {
            marginTop: '0px',
            marginBottom: '0px',
            padding: '0px',
          };
        }
        return {
          top: 0,
          padding: `32px ${this.windowIsSmall ? 16 : 32}px`,
        };
      },
      mainStyles() {
        let styles = {
          marginLeft: 'auto',
          marginRight: 'auto',
        };
        if (!this.fullScreen) {
          styles['maxWidth'] = this.maxMainWidth + 'px';
        }
        if (this.hasSidebar) {
          styles = {
            marginLeft: '0',
            marginRight: '0',
          };
        }
        return styles;
      },
    },
    methods: {
      dismissUpdateModal() {
        if (this.notifications.length === 0) {
          this.notificationModalShown = false;
          Lockr.set(UPDATE_MODAL_DISMISSED, true);
        }
      },
    },
  };

</script>


<style lang="scss" scoped>

  @import '~kolibri-design-system/lib/styles/definitions';

  .main-wrapper {
    display: inline-block;
    width: 100%;

    @media print {
      /* Without this, things won't print correctly
         *  - Firefox: Tables will get cutoff
         *  - Chrome: Table header won't repeat correctly on each page
         */
      display: block;
    }
  }

  .main {
    height: 100%;
  }

  .scrolling-pane {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow-x: auto;
  }

  .content {
    margin-right: auto;
    margin-bottom: 128px;
    margin-left: auto;
  }

</style>
