# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 17:16
from __future__ import unicode_literals

from django.db import migrations

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [("content", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="channelmetadatacache",
            name="last_updated",
            field=kolibri.core.fields.DateTimeTzField(null=True),
        )
    ]
