# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 19:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("content", "0002_channelmetadatacache_last_updated")]

    operations = []
