# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("content", "0006_auto_20171128_1703")]

    operations = [migrations.AlterModelManagers(name="contentnode", managers=[])]
