# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_auto_20180429_1709"),
        ("content", "0009_auto_20180410_1139"),
    ]

    operations = []
