# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 20:52
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

from kolibri.core.content.utils.annotation import calculate_channel_fields


def calculate_fields(apps, schema_editor):
    ChannelMetadata = apps.get_model('content', 'ChannelMetadata')
    for channel in ChannelMetadata.objects.all():
        calculate_channel_fields(channel.id)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_merge_20180504_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmetadata',
            name='included_languages',
            field=models.ManyToManyField(blank=True, related_name='channels', to='content.Language', verbose_name='languages'),
        ),
        migrations.AddField(
            model_name='channelmetadata',
            name='published_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelmetadata',
            name='total_resource_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunPython(calculate_fields, migrations.RunPython.noop),
    ]
