# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 20:52
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("content", "0010_merge_20180504_1540")]

    operations = [
        migrations.AddField(
            model_name="channelmetadata",
            name="included_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="channels",
                to="content.Language",
                verbose_name="languages",
            ),
        ),
        migrations.AddField(
            model_name="channelmetadata",
            name="published_size",
            field=models.IntegerField(default=0, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelmetadata",
            name="total_resource_count",
            field=models.IntegerField(default=0, blank=True, null=True),
        ),
    ]
