# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 00:02
from __future__ import unicode_literals

from django.db import migrations

from kolibri.core.content.utils.annotation import calculate_channel_fields


def calculate_fields(apps, schema_editor):
    ChannelMetadata = apps.get_model('content', 'ChannelMetadata')
    for channel in ChannelMetadata.objects.all():
        calculate_channel_fields(channel.id)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180907_1017'),
    ]

    operations = [
        migrations.RunPython(calculate_fields, migrations.RunPython.noop),
    ]
