# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 20:20
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20181218_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='importable',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='file',
            name='importable',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='localfile',
            name='importable',
            field=models.NullBooleanField(),
        ),
    ]
