# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 00:39
from __future__ import unicode_literals

from django.db import migrations


def calculate_next_order(channel, model):
    """
    See kolibri.core.content.utils.annotation.calculate_next_order
    """
    latest_order = model.objects.latest("order").order
    if latest_order is None:
        channel.order = 1
    else:
        channel.order = latest_order + 1
    channel.save()


def calculate_channel_order(apps, schema_editor):
    ChannelMetadata = apps.get_model("content", "ChannelMetadata")
    for channel in ChannelMetadata.objects.all():
        calculate_next_order(channel, ChannelMetadata)


class Migration(migrations.Migration):

    dependencies = [("content", "0015_auto_20190125_1715")]

    operations = [
        migrations.RunPython(calculate_channel_order, migrations.RunPython.noop)
    ]
