# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 16:22
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("content", "0017_auto_20190415_1855")]

    operations = [
        migrations.AddField(
            model_name="contentnode", name="importable", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="file", name="importable", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="localfile", name="importable", field=models.NullBooleanField()
        ),
    ]
