# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_contentnode_num_coach_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='stemmed_metaphone',
        ),
    ]
