# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("content", "0021_remove_contentnode_stemmed_metaphone")]

    operations = [migrations.RemoveField(model_name="file", name="available")]
