# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 19:25
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("content", "0022_remove_file_available")]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="on_device_resources",
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
