# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 22:25
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("content", "0023_contentnode_on_device_resources")]

    operations = [
        migrations.AddField(
            model_name="channelmetadata", name="public", field=models.NullBooleanField()
        )
    ]
