# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 00:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_add_h5p_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='options',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
