# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 21:17
from __future__ import unicode_literals

from django.db import migrations

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_add_h5p_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="options",
            field=kolibri.core.fields.JSONField(default={}),
        ),
    ]
