# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 20:40
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_contentnode_metadata_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="accessibility_labels_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="categories_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="grade_levels_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learner_needs_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="learning_activities_bitmask_0",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
