# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 23:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_contentnode_ancestors"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmetadata",
            name="partial",
            field=models.NullBooleanField(default=False),
        ),
    ]
