# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-15 19:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_channelmetadata_partial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="admin_imported",
            field=models.NullBooleanField(),
        ),
    ]
