# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-08 13:46
import morango.models.fields.uuids
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_content_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrequest",
            name="source_instance_id",
            field=morango.models.fields.uuids.UUIDField(blank=True, null=True),
        ),
    ]
