# Generated by Django 3.2.25 on 2024-03-22 20:41
from django.db import migrations
from django.db import models

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_add_imscp_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelmetadata",
            name="partial",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="channelmetadata",
            name="public",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="admin_imported",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="ancestors",
            field=kolibri.core.fields.JSONField(
                blank=True, default=[], load_kwargs={"strict": False}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
