# Generated by Django 3.2.25 on 2024-09-25 09:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0037_add_bloompub_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localfile",
            name="extension",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mp4", "MP4 Video"),
                    ("webm", "WEBM Video"),
                    ("vtt", "VTT Subtitle"),
                    ("mp3", "MP3 Audio"),
                    ("pdf", "PDF Document"),
                    ("jpg", "JPG Image"),
                    ("jpeg", "JPEG Image"),
                    ("png", "PNG Image"),
                    ("gif", "GIF Image"),
                    ("json", "JSON"),
                    ("svg", "SVG Image"),
                    ("perseus", "Perseus Exercise"),
                    ("graphie", "Graphie Exercise"),
                    ("zip", "HTML5 Zip"),
                    ("h5p", "H5P"),
                    ("zim", "ZIM"),
                    ("epub", "ePub Document"),
                    ("bloompub", "Bloom Document"),
                    ("bloomd", "Bloom Document"),
                ],
                max_length=40,
            ),
        ),
    ]
