# Generated by Django 3.2.25 on 2024-12-13 17:17
import sortedm2m.fields
import sortedm2m.operations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0038_alter_localfile_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmetadata",
            name="included_categories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelmetadata",
            name="included_grade_levels",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="channelmetadata",
            name="included_languages",
        ),
        migrations.AddField(
            model_name="channelmetadata",
            name="included_languages",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="channels",
                to="content.Language",
                verbose_name="languages",
            ),
        ),
    ]
