# Generated by Django 3.2.25 on 2024-12-18 00:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0039_channelmetadata_ordered_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="included_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="contentnodes",
                to="content.Language",
                verbose_name="languages",
            ),
        ),
    ]
