# Generated by Django 3.2.25 on 2026-08-02
import sortedm2m.fields
from django.db import migrations


def backfill_contentnode_included_languages(apps, schema_editor):
    ContentNode = apps.get_model("content", "ContentNode")
    through = ContentNode.included_languages.through
    connection = schema_editor.connection
    node_table = ContentNode._meta.db_table
    through_table = through._meta.db_table
    source_column = through._meta.get_field("contentnode").column
    target_column = through._meta.get_field("language").column
    sort_column = through._meta.get_field("sort_value").column

    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO {through_table} "
            "({source_column}, {target_column}, {sort_column}) "
            "SELECT ancestor.id, descendant.lang_id, 0 "
            "FROM {node_table} ancestor "
            "JOIN {node_table} descendant ON "
            "ancestor.tree_id = descendant.tree_id AND "
            "descendant.lft >= ancestor.lft AND "
            "descendant.rght <= ancestor.rght "
            "WHERE descendant.available = %s AND "
            "descendant.lang_id IS NOT NULL "
            "GROUP BY ancestor.id, descendant.lang_id".format(
                through_table=connection.ops.quote_name(through_table),
                source_column=connection.ops.quote_name(source_column),
                target_column=connection.ops.quote_name(target_column),
                sort_column=connection.ops.quote_name(sort_column),
                node_table=connection.ops.quote_name(node_table),
            ),
            [True],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0039_channelmetadata_ordered_fields"),
    ]

    run_before = [
        ("content", "0041_contentnode_modality"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="included_languages",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="contentnodes",
                to="content.Language",
                verbose_name="languages",
            ),
        ),
        migrations.RunPython(
            backfill_contentnode_included_languages, migrations.RunPython.noop
        ),
    ]
