# Generated by Django 3.2.25 on 2026-01-07 12:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0040_html_article_constants"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COURSE", "Course"),
                    ("CUSTOM_NAVIGATION", "Custom Navigation"),
                    ("LESSON", "Lesson"),
                    ("QUIZ", "Quiz"),
                    ("SURVEY", "Survey"),
                    ("UNIT", "Unit"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
    ]
