# Generated by Django 3.2.25 on 2026-01-16 11:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0041_contentnode_modality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentnode",
            name="modality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COURSE", "Course"),
                    ("CUSTOM_NAVIGATION", "Custom Navigation"),
                    ("LESSON", "Lesson"),
                    ("QUIZ", "Quiz"),
                    ("SURVEY", "Survey"),
                    ("UNIT", "Unit"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(
                fields=["modality"], name="content_con_modalit_b33128_idx"
            ),
        ),
    ]
