"""
This module manages the interface between webpack and Django.
It loads webpack bundle tracker stats files, and catalogues the different files
that need to be served in order to inject that frontend code into a Django template.
Originally, it was a monkeypatch of django-webpack-loader - but as our needs are somewhat
different, much of the code has simply been rewritten, and will continue to be done so to better much our use case.
"""
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings
from django.utils.safestring import mark_safe


def render_as_url(chunk):
    """
    This function returns the URL for a particular chunk (JS or CSS file), by
    appending the url or public path for the file to the current STATIC_URL set
    in settings.

    :param chunk: A dictionary with a url or publicPath attribute -
    this is generated by Webpack.

    :returns: The URL to the file for the client.
    """
    static = getattr(settings, 'STATIC_URL')
    url = chunk.get('publicPath') or chunk['url']
    return "{static}{url}".format(static=static, url=url)


def webpack_asset_render(HookClass, async=False):
    """
    This is produces content for a  script tag for a WebpackInclusionHook subclass that implement
    different render to html methods either sync or async.
    :param HookClass: a subclass of WebpackInclusionHook
    :param sync: Render sync or async.
    :return: HTML of script tags to insert
    """
    tags = []
    for hook in HookClass().registered_hooks:
        tags.append(
            hook.render_to_page_load_sync_html() if not async else hook.render_to_page_load_async_html()
        )
    return mark_safe('\n'.join(tags))
