# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 04:53
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("device", "0003_contentcachekey")]

    operations = [
        migrations.AlterField(
            model_name="devicesettings",
            name="language_id",
            field=models.CharField(blank=True, default="en", max_length=15, null=True),
        )
    ]
