# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 17:51
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_auto_20190306_0553"),
        ("kolibriauth", "0012_facilitydataset_allow_guest_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="allow_guest_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="allow_learner_unassigned_resource_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="allow_peer_unlisted_channel_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="landing_page",
            field=models.CharField(
                choices=[("sign-in", "Sign-in page"), ("learn", "Learn page")],
                default="sign-in",
                max_length=7,
            ),
        ),
    ]
