# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 17:43
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.device.models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_migrate_guest_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcachekey",
            name="key",
            field=models.BigIntegerField(
                default=kolibri.core.device.models.generate_content_cache_key
            ),
        ),
    ]
