# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-27 01:05
from __future__ import unicode_literals

import uuid

import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("device", "0006_migrate_guest_access")]

    operations = [
        migrations.CreateModel(
            name="DeviceAppKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", morango.models.fields.uuids.UUIDField(default=uuid.uuid4)),
            ],
        )
    ]
