# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 17:37
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.device.models


class Migration(migrations.Migration):

    dependencies = [("device", "0006_migrate_guest_access")]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="name",
            field=models.CharField(
                default=kolibri.core.device.models.get_device_hostname, max_length=50
            ),
        )
    ]
