# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 17:11
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.device.models


class Migration(migrations.Migration):

    dependencies = [("device", "0007_deviceappkey")]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="allow_other_browsers_to_connect",
            field=models.BooleanField(
                default=kolibri.core.device.models.app_is_enabled
            ),
        )
    ]
