# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_deviceappkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="allow_other_browsers_to_connect",
            field=models.NullBooleanField(),
        ),
    ]
