# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_deviceappkey"),
        ("device", "0007_devicesettings_name"),
    ]

    operations = []
