# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_merge_20200531_1829"),
        ("device", "0008_devicesettings_allow_other_browsers_to_connect"),
    ]

    operations = []
