# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-27 14:37
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_sqlitelock"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="subset_of_users_device",
            field=models.BooleanField(default=False),
        ),
    ]
