# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-30 15:30
from __future__ import unicode_literals

import time
import uuid

import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0019_collection_no_mptt"),
        ("device", "0011_devicesettings_subset_of_users_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", morango.models.fields.uuids.UUIDField(default=uuid.uuid4)),
                ("instance_id", morango.models.fields.uuids.UUIDField(unique=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("updated", models.FloatField(default=time.time)),
                ("keep_alive", models.FloatField(default=5.0)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.Facility",
                    ),
                ),
            ],
        ),
    ]
