# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-24 17:37
from __future__ import unicode_literals

from uuid import uuid4

import morango.models.fields.uuids
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0013_usersyncstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncqueue",
            name="instance_id",
            field=morango.models.fields.uuids.UUIDField(default=uuid4),
            preserve_default=False,
        ),
    ]
