# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-26 18:13
from django.db import migrations

import kolibri.core.device.models
import kolibri.core.fields
import kolibri.core.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0016_osuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="extra_settings",
            field=kolibri.core.fields.JSONField(
                default=kolibri.core.device.models.extra_settings_default_values,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        kolibri.core.device.models.extra_settings_schema
                    )
                ],
            ),
        ),
    ]
