# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 15:46
import django.db.models.deletion
import morango.models.fields.uuids
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0020_facilitydataset_extra_fields"),
        ("device", "0017_extra_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerDeviceStatus",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                ("instance_id", morango.models.fields.uuids.UUIDField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=32)),
                (
                    "status_sentiment",
                    models.IntegerField(
                        choices=[("Negative", -1), ("Neutral", 0), ("Positive", 1)]
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.FacilityDataset",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_device_status",
                        to="kolibriauth.FacilityUser",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="learnerdevicestatus",
            unique_together=set([("instance_id", "user")]),
        ),
    ]
