# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-20 16:16
import django.db.models.deletion
import morango.models.fields.uuids
from django.db import connection
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0018_add_learner_device_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersyncstatus",
            name="queued",
        ),
        migrations.RunSQL(
            [
                "DELETE FROM device_syncqueue;"
                if "sqlite" in connection.vendor
                else "TRUNCATE TABLE device_syncqueue;"
            ],
            hints={"is_syncqueue": True},
        ),
        migrations.AddField(
            model_name="syncqueue",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncqueue",
            name="last_sync",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("INELIGIBLE", "Ineligible"),
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("READY", "Ready"),
                    ("STALE", "Stale"),
                    ("SYNCING", "Syncing"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="syncqueue",
            name="sync_session_id",
            field=morango.models.fields.uuids.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersyncstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("INELIGIBLE", "Ineligible"),
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("READY", "Ready"),
                    ("STALE", "Stale"),
                    ("SYNCING", "Syncing"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersyncstatus",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usersyncstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kolibriauth.FacilityUser",
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncqueue",
            unique_together=set([("user_id", "instance_id")]),
        ),
    ]
