# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-21 15:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0019_syncqueue_and_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnerdevicestatus",
            name="status_sentiment",
            field=models.IntegerField(
                choices=[(-1, "Negative"), (0, "Neutral"), (1, "Positive")]
            ),
        ),
    ]
