# Generated by Django 3.2.23 on 2024-02-10 22:08
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("kolibriauth", "0001_initial"),
        ("device", "0020_fix_learner_device_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersyncstatus",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="kolibriauth.FacilityUser",
            ),
        ),
    ]
