# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-14 21:54
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0022_update_language_code_nyn_to_ny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnerdevicestatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learner_device_status",
                to="kolibriauth.FacilityUser",
            ),
        ),
    ]
