# Generated by Django 3.2.25 on 2024-05-16 17:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0022_alter_usersyncstatus_user"),
        ("device", "0023_learner_device_status_multiple_devices"),
    ]

    operations = []
