#!/usr/bin/env python3
"""
Generate crowdin_code mappings (Django locale, installer, Android qualifier) for crowdin.yml.
"""

from build_tools.i18n.utils import available_languages
from build_tools.i18n.utils import to_locale

# Script subtags (es-419, zh-hans) can't be derived by to_android_locale's
# region logic (segment 2 -> -rXX), so list them explicitly here, keyed by
# intl_code. Add any future script-suffixed intl code here too.
ANDROID_LOCALE_OVERRIDES = {
    "es-419": "b+es+419",
    "zh-hans": "zh",
}


def to_android_locale(intl_code):
    """Convert a Kolibri intl code to an Android values-<code> qualifier."""
    if intl_code in ANDROID_LOCALE_OVERRIDES:
        return ANDROID_LOCALE_OVERRIDES[intl_code]
    parts = intl_code.split("-")
    if len(parts) == 1:
        return intl_code
    if len(parts) == 2:
        return f"{parts[0]}-r{parts[1].upper()}"
    raise ValueError(f"Invalid intl code: {intl_code}")


def get_android_language_mapping():
    """Map each crowdin_code to its Android values-<code> qualifier."""
    return {
        lang["crowdin_code"]: to_android_locale(lang["intl_code"])
        for lang in available_languages()
    }


def get_language_mapping():
    """Map each crowdin_code to its Django locale code (underscore format)."""
    # to_locale handles script suffixes like 'hans' correctly
    return {
        lang["crowdin_code"]: to_locale(lang["intl_code"])
        for lang in available_languages()
    }


def get_installer_language_mapping():
    """Map crowdin_code -> raw intl_code (hyphen-lowercase), matching the
    desktop-app installer's locale folder convention."""
    return {lang["crowdin_code"]: lang["intl_code"] for lang in available_languages()}


def main():
    """Print the Django-locale, Android, and installer mappings for crowdin.yml."""
    print("# Generated mapping from crowdin_code to Django locale code")  # noqa: T201
    print("# Generated by build_tools/i18n/generate_mapping.py")  # noqa: T201
    for crowdin_code, locale_code in sorted(get_language_mapping().items()):
        print(f'  "{crowdin_code}": "{locale_code}",')  # noqa: T201

    print()  # noqa: T201
    print("# Generated mapping from crowdin_code to Android values-<code> qualifier")  # noqa: T201
    print("# Generated by build_tools/i18n/generate_mapping.py")  # noqa: T201
    print('  "android_code":')  # noqa: T201
    for crowdin_code, android_code in sorted(get_android_language_mapping().items()):
        print(f'    "{crowdin_code}": "{android_code}",')  # noqa: T201

    print("  # Installer (hyphen-lowercase) mapping — %locale% placeholder")  # noqa: T201
    for crowdin_code, intl_code in sorted(get_installer_language_mapping().items()):
        print(f'  "{crowdin_code}": "{intl_code}",')  # noqa: T201


if __name__ == "__main__":
    main()
