#!/usr/bin/env python3
"""
Generate crowdin_code mappings (Django locale, installer, Android qualifier) and the
installer messages.isl exclusions for crowdin.yml.
"""

import importlib.util
import json
import os

from build_tools.i18n.utils import available_languages
from build_tools.i18n.utils import to_locale

INSTALLER_DEFINITIONS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "platforms",
    "desktop-app",
    "installer",
    "translations",
    "definitions.py",
)

# Script subtags (es-419, zh-hans) can't be derived by to_android_locale's
# region logic (segment 2 -> -rXX), so list them explicitly here, keyed by
# intl_code. Add any future script-suffixed intl code here too.
ANDROID_LOCALE_OVERRIDES = {
    "es-419": "b+es+419",
    "zh-hans": "zh",
}


def to_android_locale(intl_code):
    """Convert a Kolibri intl code to an Android values-<code> qualifier."""
    if intl_code in ANDROID_LOCALE_OVERRIDES:
        return ANDROID_LOCALE_OVERRIDES[intl_code]
    parts = intl_code.split("-")
    if len(parts) == 1:
        return intl_code
    if len(parts) == 2:
        return f"{parts[0]}-r{parts[1].upper()}"
    raise ValueError(f"Invalid intl code: {intl_code}")


def get_android_language_mapping():
    """Map each crowdin_code to its Android values-<code> qualifier."""
    return {
        lang["crowdin_code"]: to_android_locale(lang["intl_code"])
        for lang in available_languages()
    }


def get_language_mapping():
    """Map each crowdin_code to its Django locale code (underscore format)."""
    # to_locale handles script suffixes like 'hans' correctly
    return {
        lang["crowdin_code"]: to_locale(lang["intl_code"])
        for lang in available_languages()
    }


def get_installer_language_mapping():
    """Map crowdin_code -> raw intl_code (hyphen-lowercase), matching the
    desktop-app installer's locale folder convention."""
    return {lang["crowdin_code"]: lang["intl_code"] for lang in available_languages()}


def _installer_definitions():
    # definitions.py sits outside the kolibri_app package, so it is not importable.
    spec = importlib.util.spec_from_file_location(
        "installer_definitions", INSTALLER_DEFINITIONS
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.LANG_DEFINITIONS


def get_installer_excluded_languages():
    """Crowdin codes to exclude from the installer's messages.isl.

    Inno Setup supplies the [Messages] section for most languages, and only those
    without a translation of it (`translate_messages`) need Crowdin to translate the
    file. Excluding the rest keeps ~450 strings of Inno boilerplate off translators.
    """
    crowdin_codes = {v: k for k, v in get_installer_language_mapping().items()}
    return sorted(
        crowdin_codes[locale]
        for locale, definition in _installer_definitions().items()
        if locale != "en" and not definition.get("translate_messages")
    )


def main():
    """Print the mappings and the installer exclusions for crowdin.yml."""
    print("# Generated mapping from crowdin_code to Django locale code")  # noqa: T201
    print("# Generated by build_tools/i18n/generate_mapping.py")  # noqa: T201
    for crowdin_code, locale_code in sorted(get_language_mapping().items()):
        print(f'  "{crowdin_code}": "{locale_code}",')  # noqa: T201

    print()  # noqa: T201
    print("# Generated mapping from crowdin_code to Android values-<code> qualifier")  # noqa: T201
    print("# Generated by build_tools/i18n/generate_mapping.py")  # noqa: T201
    print('  "android_code":')  # noqa: T201
    for crowdin_code, android_code in sorted(get_android_language_mapping().items()):
        print(f'    "{crowdin_code}": "{android_code}",')  # noqa: T201

    print("  # Installer (hyphen-lowercase) mapping — %locale% placeholder")  # noqa: T201
    for crowdin_code, intl_code in sorted(get_installer_language_mapping().items()):
        print(f'  "{crowdin_code}": "{intl_code}",')  # noqa: T201

    print()  # noqa: T201
    print("# Generated installer messages.isl exclusions for crowdin.yml")  # noqa: T201
    print("# Generated by build_tools/i18n/generate_mapping.py")  # noqa: T201
    excluded = json.dumps(get_installer_excluded_languages())
    print(f'  "excluded_target_languages": {excluded},')  # noqa: T201


if __name__ == "__main__":
    main()
