DEFAULT_PLUGINS = [
    "kolibri.plugins.coach",
    "kolibri.plugins.default_theme",
    "kolibri.plugins.device",
    "kolibri.plugins.epub_viewer",
    "kolibri.plugins.html5_viewer",
    "kolibri.plugins.facility",
    "kolibri.plugins.learn",
    "kolibri.plugins.media_player",
    "kolibri.plugins.pdf_viewer",
    "kolibri.plugins.perseus_viewer",
    "kolibri.plugins.setup_wizard",
    "kolibri.plugins.slideshow_viewer",
    "kolibri.plugins.user_auth",
    "kolibri.plugins.user_profile",
]
