# Generated by Django 3.2.25 on 2026-02-14 04:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("attendance_session", "user")},
        ),
    ]
