# Generated by Django 3.2.25 on 2024-06-07 09:20
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorReports",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_from",
                    models.CharField(
                        choices=[("frontend", "Frontend"), ("backend", "Backend")],
                        max_length=10,
                    ),
                ),
                ("error_message", models.CharField(max_length=255)),
                ("traceback", models.TextField()),
                (
                    "first_occurred",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_occurred",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent", models.BooleanField(default=False)),
                ("no_of_errors", models.IntegerField(default=1)),
            ],
        ),
    ]
