# Generated by Django 3.2.25 on 2024-07-31 16:20
from django.db import migrations
from django.db import models

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("errorreports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="errorreports",
            old_name="error_from",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="no_of_errors",
            new_name="events",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="sent",
            new_name="reported",
        ),
        migrations.AddField(
            model_name="errorreports",
            name="avg_request_time_to_error",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="context",
            field=kolibri.core.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="installation_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="release_version",
            field=models.CharField(
                blank=True, default="0.16.2b2.dev0+git.1211.gc5eb2ae8", max_length=128
            ),
        ),
    ]
