# Generated by Django 3.2.25 on 2024-08-09 23:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("errorreports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorreports",
            name="release_version",
            field=models.CharField(
                blank=True, default="0.16.2b2.dev0+git.1217.g085cf885", max_length=128
            ),
        ),
    ]
