# Generated by Django 3.2.25 on 2024-07-15 07:30
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.core.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("errorreports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="errorreports",
            old_name="error_from",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="no_of_errors",
            new_name="events",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="sent",
            new_name="reported",
        ),
        migrations.AddField(
            model_name="errorreports",
            name="context_backend",
            field=kolibri.core.fields.JSONField(
                blank=True,
                default={
                    "packages": {},
                    "python_version": "",
                    "request_info": {
                        "body": "",
                        "headers": {},
                        "method": "",
                        "url": "",
                    },
                    "server": {"host": "", "port": 0},
                },
                null=True,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "properties": {
                                "packages": {"optional": True, "type": "object"},
                                "python_version": {"optional": True, "type": "string"},
                                "request_info": {
                                    "properties": {
                                        "body": {"optional": True, "type": "string"},
                                        "headers": {"optional": True, "type": "object"},
                                        "method": {"optional": True, "type": "string"},
                                        "url": {"optional": True, "type": "string"},
                                    },
                                    "type": "object",
                                },
                                "server": {
                                    "properties": {
                                        "host": {"optional": True, "type": "string"},
                                        "port": {"optional": True, "type": "integer"},
                                    },
                                    "type": "object",
                                },
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="context_frontend",
            field=kolibri.core.fields.JSONField(
                blank=True,
                default={
                    "browser": {"major": "", "minor": "", "name": "", "patch": ""},
                    "component": "",
                    "device": {
                        "is_touch_device": False,
                        "model": "",
                        "screen": {"height": 0, "width": 0},
                        "type": "",
                        "vendor": "",
                    },
                    "os": {"major": "", "minor": "", "name": "", "patch": ""},
                },
                null=True,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "definitions": {
                                "versionInfo": {
                                    "properties": {
                                        "major": {"optional": True, "type": "string"},
                                        "minor": {"optional": True, "type": "string"},
                                        "name": {"optional": True, "type": "string"},
                                        "patch": {"optional": True, "type": "string"},
                                    },
                                    "type": "object",
                                }
                            },
                            "properties": {
                                "browser": {"$ref": "#/definitions/versionInfo"},
                                "component": {"optional": True, "type": "string"},
                                "device": {
                                    "properties": {
                                        "is_touch_device": {
                                            "optional": True,
                                            "type": "boolean",
                                        },
                                        "model": {"optional": True, "type": "string"},
                                        "screen": {
                                            "properties": {
                                                "height": {"type": "integer"},
                                                "width": {"type": "integer"},
                                            },
                                            "type": "object",
                                        },
                                        "type": {"optional": True, "type": "string"},
                                        "vendor": {"optional": True, "type": "string"},
                                    },
                                    "type": "object",
                                },
                                "os": {"$ref": "#/definitions/versionInfo"},
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="installation_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="release_version",
            field=models.CharField(default="0.16", max_length=64),
        ),
    ]
