# Generated by Django 3.2.25 on 2024-06-29 11:09
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.core.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("errorreports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="errorreports",
            old_name="error_from",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="no_of_errors",
            new_name="events",
        ),
        migrations.RenameField(
            model_name="errorreports",
            old_name="sent",
            new_name="reported",
        ),
        migrations.AddField(
            model_name="errorreports",
            name="context_backend",
            field=kolibri.core.fields.JSONField(
                blank=True,
                default={
                    "packages": {},
                    "python_version": "",
                    "request_info": {},
                    "server": {},
                },
                null=True,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "properties": {
                                "packages": {"optional": True, "type": "object"},
                                "python_version": {"optional": True, "type": "string"},
                                "request_info": {
                                    "properties": {
                                        "body": {"optional": True, "type": "string"},
                                        "headers": {"optional": True, "type": "object"},
                                        "method": {"optional": True, "type": "string"},
                                        "url": {"optional": True, "type": "string"},
                                    },
                                    "type": "object",
                                },
                                "server": {
                                    "properties": {
                                        "host": {"optional": True, "type": "string"},
                                        "port": {"optional": True, "type": "integer"},
                                    },
                                    "type": "object",
                                },
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="context_frontend",
            field=kolibri.core.fields.JSONField(
                blank=True,
                default={"browser": "", "component": "N/A", "device": {}},
                null=True,
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "properties": {
                                "browser": {"type": "string"},
                                "component": {"optional": True, "type": "string"},
                                "device": {
                                    "properties": {
                                        "platform": {
                                            "optional": True,
                                            "type": "string",
                                        },
                                        "screen": {
                                            "properties": {
                                                "height": {"type": "integer"},
                                                "width": {"type": "integer"},
                                            },
                                            "type": "object",
                                        },
                                        "type": {"type": "string"},
                                    },
                                    "type": "object",
                                },
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="errorreports",
            name="release_version",
            field=models.CharField(default="0.16", max_length=64),
        ),
    ]
