# Generated by Django 3.2.25 on 2024-09-26 01:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("errorreports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorreports",
            name="category",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("task", "Task"),
                ],
                max_length=10,
            ),
        ),
    ]
