# Generated by Django 3.2.25 on 2025-10-15 21:14
# Modified to use AddColumnIfNotExists operation to prevent errors if columns were
# added by SQLAlchemy.
from django.db import migrations
from django.db import models

from kolibri.core.tasks.operations import AddFieldIfNotExists


class Migration(migrations.Migration):

    dependencies = [
        ("kolibritasks", "0001_initial"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="job",
            name="max_retries",
            field=models.IntegerField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name="job",
            name="retries",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
