# Generated by Django 3.2.25 on 2025-10-15 21:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("kolibritasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="max_retries",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="retries",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
