name: Python tests

on: [push, pull_request]

jobs:
  pre_job:
    name: Path match check
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths: '["**.py", "pyproject.toml", "uv.lock", ".github/workflows/python.yml"]'

  unit_test:
    name: Python unit tests
    needs: pre_job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        with:
          fetch-depth: 0

      - name: Set up uv
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: 3.9
          enable-cache: true

      - name: Sync dependencies
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        run: uv sync --locked --no-dev --group test

      - name: Install and enable kolibri_sync_extras plugin
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        env:
          KOLIBRI_HOME: .kolibri
        run: uv run kolibri plugin enable kolibri_sync_extras_plugin

      - name: Run tests
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        run: uv run python -O -m pytest --reuse-db
