# Generated by Django 3.2.25 on 2026-02-02 18:04
import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitTestAssignment",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                ("unit_contentnode_id", morango.models.fields.uuids.UUIDField()),
                (
                    "test_type",
                    models.CharField(
                        choices=[("post", "Post"), ("pre", "Pre")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("not_started", "NotStarted"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_unit_tests",
                        to="kolibriauth.facilityuser",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_test_assignments",
                        to="kolibriauth.collection",
                    ),
                ),
                (
                    "course_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_test_assignments",
                        to="courses.coursesession",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.facilitydataset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
