# Generated by Django 3.2.25 on 2026-02-24 21:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_unittestassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unittestassignment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="unittestassignment",
            name="status",
        ),
        migrations.AddField(
            model_name="unittestassignment",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
