# Generated by Django 3.2.25 on 2026-04-09 21:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_unittestassignment_closed_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="channel_version",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
