"""
Write the generated installer language files: the [Languages] entries kolibri.iss
includes, and the per-language [LangOptions] each entry chains last.

The [LangOptions] override the language name, ID, font and direction that the
Inno Setup files carry, so Kolibri's own language list stays authoritative.
"""

import argparse
from pathlib import Path
from pathlib import PurePosixPath

from definitions import INNO_DEFAULT
from definitions import LANG_DEFINITIONS

# Inno Setup's setup.iss installs `files\Languages\*.isl` but not the Unofficial
# subfolder, so its official translations are already on any machine with the
# compiler and `compiler:` resolves them against the compiler doing the build.
# Only the unofficial ones have to be vendored (see update_from_inno.py).
UNOFFICIAL_DIR = "Languages/Unofficial/"


def inno_messages_file(inno_file):
    if inno_file.startswith(UNOFFICIAL_DIR):
        return "translations\\inno\\" + PurePosixPath(inno_file).name
    return "compiler:" + inno_file.replace("/", "\\")


def messages_files(locale_code, definition, locale_dir):
    """The MessagesFile chain for one language, in the order Inno reads it.

    Each file overrides the ones before it, so this runs from the most general
    fallback to the most specific: Inno's English, Inno's own translation, the
    Crowdin translations, then our [LangOptions]. A Crowdin file that no one has
    translated yet is absent from the tree and simply drops out of the chain.
    """
    chain = ["compiler:" + INNO_DEFAULT]

    if "inno_file" in definition:
        chain.append(inno_messages_file(definition["inno_file"]))

    if definition.get("translate_messages"):
        chain.append(translation_file(locale_code, "messages.isl", locale_dir))

    chain.append("translations\\locale\\en\\custom.isl")
    if locale_code != "en":
        chain.append(translation_file(locale_code, "custom.isl", locale_dir))

    chain.append(f"translations\\langoptions\\{locale_code}.isl")
    return [entry for entry in chain if entry]


def translation_file(locale_code, name, locale_dir):
    if not (locale_dir / locale_code / name).is_file():
        return None
    return f"translations\\locale\\{locale_code}\\{name}"


def lang_options(definition):
    options = [
        ("LanguageName", definition["display_name"]),
        ("LanguageID", definition["id"]),
        ("LanguageCodePage", "0"),
    ]
    if "font" in definition:
        options.append(("DialogFontName", definition["font"]))
        options.append(("WelcomeFontName", definition["font"]))
    if definition.get("rtl"):
        options.append(("RightToLeft", "yes"))
    return options


def write_languages(languages_path, locale_dir):
    lines = [f"; Generated by {Path(__file__).name} — do not edit."]
    for locale_code, definition in LANG_DEFINITIONS.items():
        name = locale_code.replace("-", "_")
        files = ",".join(messages_files(locale_code, definition, locale_dir))
        lines.append(f'Name: "{name}"; MessagesFile: "{files}"')
    languages_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  -> {languages_path.name}")  # noqa: T201


def write_lang_options(output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)
    for locale_code, definition in LANG_DEFINITIONS.items():
        lines = ["[LangOptions]"]
        lines.extend(f"{key}={value}" for key, value in lang_options(definition))
        path = output_dir / f"{locale_code}.isl"
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  -> {path.name}")  # noqa: T201


def main(translations_dir):
    write_languages(translations_dir / "languages.iss", translations_dir / "locale")
    write_lang_options(translations_dir / "langoptions")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-d",
        "--translations-dir",
        type=Path,
        default=Path(__file__).parent,
        help="The installer translations directory",
    )
    args = parser.parse_args()

    main(args.translations_dir)
