project_identifier_env: CROWDIN_PROJECT
api_key_env: CROWDIN_API_KEY
base_path: .

files:
  - source: '/locale/docs/en/LC_MESSAGES/*.po'
    translation: '/locale/docs/%locale_with_underscore%/LC_MESSAGES/%original_file_name%'
