# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 21:59
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("exams", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="data_model_version",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="learners_see_fixed_order",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(model_name="exam", name="channel_id"),
    ]
