# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 17:15
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("exams", "0002_update_exam_data_model")]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="data_model_version",
            field=models.SmallIntegerField(default=2),
        )
    ]
