# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0003_auto_20190426_1015")]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # Ensure that previously created exams have no created_at by default.
        migrations.RunSQL(
            sql="UPDATE exams_exam SET date_created=NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
