# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-19 20:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_individualsyncableexam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
