# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 20:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_nullable_creator_assigned_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="data_model_version",
            field=models.SmallIntegerField(default=3),
        ),
    ]
