# Generated by Django 3.2.25 on 2024-07-03 21:46
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_draft_exams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
