# Generated by Django 3.2.25 on 2026-05-27 03:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0010_add_exam_report_visibility_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftexam",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draftexams",
                to="kolibriauth.FacilityUser",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="kolibriauth.FacilityUser",
            ),
        ),
        migrations.AlterField(
            model_name="examassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_exams",
                to="kolibriauth.FacilityUser",
            ),
        ),
    ]
