name: Publish package to npm

on:
    workflow_dispatch:
      # Inputs the workflow accepts.
      inputs:
        npm_package:
          description: 'Package to publish to NPM'
          required: true
          type: choice
          options:
            - 'browserslist-config-kolibri'
            - 'eslint-plugin-kolibri'
            - 'kolibri'
            - 'kolibri-app'
            - 'kolibri-build'
            - 'kolibri-format'
            - 'kolibri-glob'
            - 'kolibri-i18n'
            - 'kolibri-jest-config'
            - 'kolibri-logging'
            - 'kolibri-module'
            - 'kolibri-plugin-data'
            - 'kolibri-tools'
            - 'kolibri-viewer'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for npm provenance
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            const packageJson = require(`./packages/${{ github.event.inputs.npm_package }}/package.json`)
            const version = packageJson.version
            const tagname = `npm/${{ github.event.inputs.npm_package }}/${version}`
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagname}`,
              sha: context.sha
            })
      - name: Build package
        run: pnpm --filter ${{ github.event.inputs.npm_package }} run build || true
      - name: Publish to npm
        run: pnpm --filter ${{ github.event.inputs.npm_package }} publish --provenance --access public --no-git-checks
        env:
          # NPM_API_TOKEN is an organization-level secret
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
