name: Build Asset Comment for Pull Request

on:
  workflow_run:
    workflows: [Kolibri Build Assets for Pull Request]
    types:
      - completed

jobs:
  post:
    name: Add build artifact PR comment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
      - uses: actions/checkout@v6
      - name: Make text for build comment
        id: comment-text
        uses: actions/github-script@v9
        with:
          script: |
            const utils = require('./.github/githubUtils.js')
            return await utils.generateAssetComment(github, context)
      - name: Unzip PR number artifact
        run: unzip pr_number.zip
      - name: Get PR number
        id: pr-number
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs');
            const prNumber = Number(fs.readFileSync('./pr_number'));
            return prNumber
      - name: Post build comment
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const utils = require('./.github/githubUtils.js')
            await utils.upsertComment(github, context, ${{steps.pr-number.outputs.result}}, '**Build Artifacts**', ${{ steps.comment-text.outputs.result }})
