name: Upload Python Package
on:
  workflow_call:
    inputs:
      whl-file-name:
        required: true
        type: string
      tar-file-name:
        required: true
        type: string
      test:
        description: 'Should this be uploaded to testpypi?'
        required: true
        type: boolean
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.whl-file-name }}
          path: dist
      - uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.tar-file-name }}
          path: dist
      - name: Publish to TestPyPi
        if: ${{ inputs.test }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPi
        if: ${{ !inputs.test }}
        uses: pypa/gh-action-pypi-publish@release/v1
